@startuml UTS

[*] --> Daftar_Baju
Daftar_Baju : 1. Team Ferrari
Daftar_Baju : 2. Team Mercedes
Daftar_Baju : 3. Team Redbull Racing
Daftar_Baju --> Input_Team
Input_Team: Pilih nomor tim Formula 1 yang Anda inginkan
Input_Team --> Input_Jumlah 
Input_Jumlah : Masukkan jumlah baju yang ingin Anda beli
Input_Jumlah --> Input_Keputusan
Input_Keputusan : Apakah ingin melanjutkan pembelian? (y/n)
Input_Keputusan --> N
N -->SYSTEMCLOSE
Input_Keputusan --> Y
Y : Kembali ke Daftar Baju
Y --> Daftar_Baju
SYSTEMCLOSE :   Program Selesai

@enduml